'use client';

import { motion } from 'framer-motion';
import { Shield, Download, ArrowLeft, Lock, Eye, Database, Mail, Globe, FileText, User } from 'lucide-react';
import Link from 'next/link';
import Navigation from '@/app/components/Navigation';
import Footer from '@/app/components/Footer';

const sections = [
  {
    id: 'overview',
    icon: Shield,
    title: 'Overview',
    body: (
      <>
        <p>
          Precision Project Flow ("PPF", "we", "us", or "our") is a B2B marketplace that connects
          engineers, vendors, and suppliers with clients for precision manufacturing and engineering
          services. This Privacy Policy explains what information we collect when you use our
          application, how we use it, and the choices you have about your data.
        </p>
        <p>
          <strong>Our core commitment is simple: we never sell your personal data.</strong> We do not
          sell, rent, trade, or otherwise disclose your personal information to third parties for their
          own marketing or advertising purposes. Your data is used only to operate, improve, and secure
          the PPF platform.
        </p>
      </>
    ),
  },
  {
    id: 'information-we-collect',
    icon: Database,
    title: 'Information We Collect',
    body: (
      <>
        <p>We collect the information you provide directly, plus limited data generated by your use of the platform:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Account information</strong> — your name, email address, and password (stored as a secure hash).</li>
          <li><strong>Profile information</strong> — your company name, bio, location, avatar, skills, certifications, and portfolio details you choose to share.</li>
          <li><strong>Transaction information</strong> — RFQs you post, proposals you submit, messages you send, orders, contracts, and token transactions.</li>
          <li><strong>Payment information</strong> — processed securely by Stripe. We do not store your full card number on our servers.</li>
          <li><strong>Usage information</strong> — pages visited, features used, and device/browser details to keep the platform reliable and secure.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'how-we-use',
    icon: Eye,
    title: 'How We Use Your Information',
    body: (
      <>
        <p>We use your information strictly to operate and improve the PPF marketplace:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>To create and manage your account and profile.</li>
          <li>To connect engineers and vendors with clients through RFQs, proposals, and messaging.</li>
          <li>To process payments, token purchases, and escrow transactions.</li>
          <li>To send transactional notifications (e.g., "a vendor responded to your RFQ").</li>
          <li>To detect and prevent fraud, abuse, and security threats.</li>
          <li>To comply with legal obligations and enforce our Terms of Service.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'what-we-never-do',
    icon: Lock,
    title: 'What We Never Do',
    body: (
      <>
        <p>To be completely clear about our data practices:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>We never sell your personal data.</strong> Not to advertisers, not to data brokers, not to anyone.</li>
          <li>We never share your contact information with other users without your consent.</li>
          <li>We never use your private messages or RFQ content for advertising.</li>
          <li>We never store your full payment card details.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'sharing',
    icon: Globe,
    title: 'When We Share Information',
    body: (
      <>
        <p>
          We only share information in the limited circumstances necessary to run the platform, and never
          for third-party advertising:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>With other users</strong> — the profile and service information you choose to make public, and messages you send.</li>
          <li><strong>With service providers</strong> — trusted vendors (such as Stripe for payments, Supabase for hosting, and Resend for email) who process data on our behalf under strict confidentiality.</li>
          <li><strong>For legal reasons</strong> — when required by law, subpoena, or to protect the rights and safety of our users.</li>
          <li><strong>In a business transfer</strong> — if PPF is acquired or merged, your data may transfer as part of the business, subject to this policy.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'data-security',
    icon: Lock,
    title: 'Data Security',
    body: (
      <>
        <p>
          We use industry-standard safeguards to protect your information, including encryption in transit
          (TLS), encryption at rest, and role-based access controls. Authentication is handled by Supabase
          Auth, and payments are processed by Stripe's PCI-compliant infrastructure.
        </p>
        <p>
          While no method of transmission or storage is 100% secure, we work continuously to protect your
          data and will notify you promptly in the event of a breach that affects your information.
        </p>
      </>
    ),
  },
  {
    id: 'retention',
    icon: Database,
    title: 'Data Retention',
    body: (
      <>
        <p>
          We retain your information for as long as your account is active or as needed to provide you the
          platform. If you delete your account, we will delete or anonymize your personal information,
          except where we are required to retain it for legal, accounting, or fraud-prevention purposes.
        </p>
      </>
    ),
  },
  {
    id: 'your-rights',
    icon: User,
    title: 'Your Rights & Choices',
    body: (
      <>
        <p>You have control over your data. You may:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Access and update</strong> your profile information at any time from your account settings.</li>
          <li><strong>Delete</strong> your account and associated data by contacting us.</li>
          <li><strong>Opt out</strong> of non-essential communications.</li>
          <li><strong>Request a copy</strong> of the personal data we hold about you.</li>
        </ul>
        <p>
          To exercise any of these rights, contact us at the address below. We will respond within a
          reasonable timeframe.
        </p>
      </>
    ),
  },
  {
    id: 'cookies',
    icon: FileText,
    title: 'Cookies & Tracking',
    body: (
      <>
        <p>
          We use essential cookies and similar technologies to keep you signed in and to remember your
          preferences. We may use limited analytics to understand aggregate usage, but we do not use
          third-party advertising trackers or sell data derived from cookies.
        </p>
      </>
    ),
  },
  {
    id: 'children',
    icon: Shield,
    title: "Children's Privacy",
    body: (
      <>
        <p>
          PPF is a business-to-business marketplace and is not intended for children under 18. We do not
          knowingly collect personal information from children. If you believe a child has provided us
          personal information, contact us and we will delete it.
        </p>
      </>
    ),
  },
  {
    id: 'changes',
    icon: FileText,
    title: 'Changes to This Policy',
    body: (
      <>
        <p>
          We may update this Privacy Policy from time to time. When we make material changes, we will
          update the "Last updated" date and notify you through the platform or by email where appropriate.
          Continued use of the platform after changes take effect constitutes acceptance of the updated
          policy.
        </p>
      </>
    ),
  },
  {
    id: 'contact',
    icon: Mail,
    title: 'Contact Us',
    body: (
      <>
        <p>If you have questions about this Privacy Policy or how we handle your data, please contact us:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Email:</strong> <a href="mailto:privacy@precisionprojectflow.com" className="text-[#003D82] hover:underline">privacy@precisionprojectflow.com</a></li>
          <li><strong>Support:</strong> via the <Link href="/contact" className="text-[#003D82] hover:underline">Contact page</Link></li>
        </ul>
      </>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] font-jakarta">
      <Navigation />

      <div className="pt-24 pb-12 px-4">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-10"
          >
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-6 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              <span className="text-sm font-medium">Back to home</span>
            </Link>

            <div className="flex items-center gap-4 mb-4">
              <div className="w-16 h-16 bg-[#003D82] rounded-2xl flex items-center justify-center">
                <Shield className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
                <p className="text-gray-600 mt-1">Last updated: September 2026</p>
              </div>
            </div>

            <p className="text-gray-600 mb-6">
              Your privacy matters to us. This policy explains how Precision Project Flow collects, uses,
              and protects your personal information — and our firm commitment that we never sell your data.
            </p>

            <a
              href="/Privacy%20Policy_joshgoto.pdf"
              download
              className="inline-flex items-center gap-2 px-6 py-3 bg-[#003D82] hover:bg-[#002960] text-white font-semibold rounded-xl transition-all shadow-lg hover:shadow-xl"
            >
              <Download className="w-5 h-5" />
              Download PDF
            </a>
          </motion.div>

          {/* Table of contents */}
          <motion.nav
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05 }}
            className="mb-10 p-6 bg-white rounded-2xl border border-gray-100 shadow-sm"
          >
            <h2 className="text-lg font-bold text-gray-900 mb-4">Contents</h2>
            <ul className="grid sm:grid-cols-2 gap-2">
              {sections.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="flex items-center gap-2 text-sm text-gray-600 hover:text-[#003D82] transition-colors"
                  >
                    <s.icon className="w-4 h-4 text-[#003D82]" />
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </motion.nav>

          {/* Sections */}
          <div className="space-y-6">
            {sections.map((s, i) => (
              <motion.section
                key={s.id}
                id={s.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 + i * 0.03 }}
                className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center">
                    <s.icon className="w-5 h-5 text-[#003D82]" />
                  </div>
                  <h2 className="text-xl font-bold text-gray-900">{s.title}</h2>
                </div>
                <div className="text-gray-700 leading-relaxed space-y-4">{s.body}</div>
              </motion.section>
            ))}
          </div>

          {/* Quick Links */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-8 p-6 bg-white rounded-2xl border border-gray-100 shadow-sm"
          >
            <h2 className="text-xl font-bold text-gray-900 mb-4">Related Documents</h2>
            <div className="flex flex-wrap gap-4">
              <Link
                href="/terms-of-service"
                className="flex items-center gap-2 px-6 py-3 bg-gray-100 hover:bg-gray-200 text-gray-700 font-semibold rounded-xl transition-all"
              >
                Terms of Service
              </Link>
              <Link
                href="/contact"
                className="flex items-center gap-2 px-6 py-3 bg-gray-100 hover:bg-gray-200 text-gray-700 font-semibold rounded-xl transition-all"
              >
                Contact Support
              </Link>
            </div>
          </motion.div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
